[package]
name = "Subsidies"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
WAL = { local = "../wal" }
Walrus = { local = "../walrus" }

[addresses]
subsidies = "0x0"
